config/routes.rb
Rails.application.routes.draw do
  
  resources :challenges
  
  get 'index', to: 'home#index'
  get 'about', to: 'home#about'
  
  root "home#index"

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  validates_presence_of :from, :to
end

app/models/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
    @challenge = Challenge.new
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def index
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params)
    
    if @challenge.save(challenge_params)
      flash[:success] = "New challenge has been created"
      redirect_to root_path
    else
      flash.now[:danger] = "An error has ocurred"
      render :new
    end
  end

  private

    def challenge_params
      params.require(:challenge).permit(:from, :to)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_icon(action)
    case action
    when "danger"
      fa_icon "warning"
    when "success"
      fa_icon "check"
    else
      fa_icon "info"
    end
  end
end

app/views/challenges/_form.html.erb
<%= simple_form_for @challenge do |f| %>
  <%= f.input :from, hint: 'your mother likes' %>
  <%= f.input :to %>
  <%= f.input :deadline, 
    as: :datetime, 
    order: [:day, :month, :year],
    start_year: Date.today.year
  %>
  <%= f.input :deadline, as: :string, input_html: { 'data-provide' => 'datepicker' }  %>
  <%= f.submit %>
<% end %>

app/views/challenges/index.html.erb
<div class="starter-template">
  <h1>Bootstrap starter template</h1>
  <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
</div>

app/views/challenges/new.html.erb
<h1>New challenge</h1>

<%= render 'form' %>
<%= link_to 'Home', root_path %>

app/views/home/about.html.erb
<div class="row about-content">
  <div class="col-md-6">
    <h3>Glyphicon test</h3>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      Enter a valid email address
    </div>

    <button type="button" class="btn btn-default" aria-label="Left Align">
      <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
    </button>

    <button type="button" class="btn btn-default btn-lg">
      <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Star
    </button>

  </div>

  <div class="col-md-6">
    <h3>Font Awesome test</h3>

    <%= fa_icon "warning-sign" %>
    <%= fa_stacked_icon "terminal inverse", base: "square", class: "pull-right", text: "Hi!" %>

    <br><br>

    <%= fa_stacked_icon "dollar inverse", base: "circle", class: "fa-5x" %>

    <h3>Image</h3>
    <%= image_tag 'indio.jpg' %>
  </div>
</div>



app/views/home/index.html.erb
<div class="jumbotron">
  <h2>Challenge your friends to try his honor</h2>
  <p>It's so easy, just follow the next steps:</p>
  <ol>
    <li>Choose your challenge</li>
    <li>Choose your enemy</li>
    <li>Fix a deadline</li>
    <li>Wait your price in revenge or humiliation form</li>
  </ol>
  <p style='margin-top: 30px'>
    <%= link_to 'Start now »', new_challenge_path, class: 'btn btn-lg btn-primary', role: 'button' %>
  </p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dont't be a coward!", root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to 'About', about_path %></li>
        <li class="<%= 'active' if current_page?(new_challenge_path) %>"><%= link_to 'New challenge!', new_challenge_path %></li>
        <li><%= mail_to 'carlos@guzmanweb.com', 'Contact!' %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert">
    <%= notice_icon key %>
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dontbeacoward</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= render 'layouts/notice' %>
    <%= yield %>
  </div>

</body>
</html>